"""Server

Revision ID: 4c9d26ebaf75
Revises: 5b50c9939379
Create Date: 2025-07-13 19:26:13.486205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c9d26ebaf75'
down_revision = '5b50c9939379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    with op.batch_alter_table('facilitators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilitators', schema=None) as batch_op:
        batch_op.drop_column('password')

    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('facilitator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    # ### end Alembic commands ###
