"""Create users, events, sessions, and bookings tables

Revision ID: 5b50c9939379
Revises: 7749d886b521
Create Date: 2025-07-13 11:13:43.394271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b50c9939379'
down_revision = '7749d886b521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_event_id_fkey'), type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facilitator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'facilitators', ['facilitator_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('facilitator_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('bookings_event_id_fkey'), 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
